version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn build
  deploy:
    steps:
      - run:
          name: deploy master to heroku
          command: git push heroku master
workflows:
    deploy:
      jobs:
        - deploy